export interface CountryOption {
  code: string;
  name: string;
  prefix: string;
}

export const COUNTRIES: CountryOption[] = [
  { code: 'DZ', name: 'Argelia', prefix: '+213' },
  { code: 'AO', name: 'Angola', prefix: '+244' },
  { code: 'BJ', name: 'Benín', prefix: '+229' },
  { code: 'BW', name: 'Botsuana', prefix: '+267' },
  { code: 'BF', name: 'Burkina Faso', prefix: '+226' },
  { code: 'BI', name: 'Burundi', prefix: '+257' },
  { code: 'CV', name: 'Cabo Verde', prefix: '+238' },
  { code: 'CM', name: 'Camerún', prefix: '+237' },
  { code: 'TD', name: 'Chad', prefix: '+235' },
  { code: 'KM', name: 'Comoras', prefix: '+269' },
  { code: 'CG', name: 'Congo', prefix: '+242' },
  { code: 'CI', name: 'Costa de Marfil', prefix: '+225' },
  { code: 'DJ', name: 'Yibuti', prefix: '+253' },
  { code: 'EG', name: 'Egipto', prefix: '+20' },
  { code: 'ER', name: 'Eritrea', prefix: '+291' },
  { code: 'SZ', name: 'Esuatini', prefix: '+268' },
  { code: 'ET', name: 'Etiopía', prefix: '+251' },
  { code: 'GA', name: 'Gabón', prefix: '+241' },
  { code: 'GM', name: 'Gambia', prefix: '+220' },
  { code: 'GH', name: 'Ghana', prefix: '+233' },
  { code: 'GN', name: 'Guinea', prefix: '+224' },
  { code: 'GW', name: 'Guinea-Bisáu', prefix: '+245' },
  { code: 'GQ', name: 'Guinea Ecuatorial', prefix: '+240' },
  { code: 'KE', name: 'Kenia', prefix: '+254' },
  { code: 'LS', name: 'Lesoto', prefix: '+266' },
  { code: 'LR', name: 'Liberia', prefix: '+231' },
  { code: 'LY', name: 'Libia', prefix: '+218' },
  { code: 'MG', name: 'Madagascar', prefix: '+261' },
  { code: 'MW', name: 'Malaui', prefix: '+265' },
  { code: 'ML', name: 'Malí', prefix: '+223' },
  { code: 'MA', name: 'Marruecos', prefix: '+212' },
  { code: 'MU', name: 'Mauricio', prefix: '+230' },
  { code: 'MR', name: 'Mauritania', prefix: '+222' },
  { code: 'MZ', name: 'Mozambique', prefix: '+258' },
  { code: 'NA', name: 'Namibia', prefix: '+264' },
  { code: 'NE', name: 'Níger', prefix: '+227' },
  { code: 'NG', name: 'Nigeria', prefix: '+234' },
  { code: 'CF', name: 'República Centroafricana', prefix: '+236' },
  { code: 'CD', name: 'República Democrática del Congo', prefix: '+243' },
  { code: 'RW', name: 'Ruanda', prefix: '+250' },
  { code: 'ST', name: 'Santo Tomé y Príncipe', prefix: '+239' },
  { code: 'SN', name: 'Senegal', prefix: '+221' },
  { code: 'SC', name: 'Seychelles', prefix: '+248' },
  { code: 'SL', name: 'Sierra Leona', prefix: '+232' },
  { code: 'SO', name: 'Somalia', prefix: '+252' },
  { code: 'ZA', name: 'Sudáfrica', prefix: '+27' },
  { code: 'SS', name: 'Sudán del Sur', prefix: '+211' },
  { code: 'SD', name: 'Sudán', prefix: '+249' },
  { code: 'TZ', name: 'Tanzania', prefix: '+255' },
  { code: 'TG', name: 'Togo', prefix: '+228' },
  { code: 'TN', name: 'Túnez', prefix: '+216' },
  { code: 'UG', name: 'Uganda', prefix: '+256' },
  { code: 'ZM', name: 'Zambia', prefix: '+260' },
  { code: 'ZW', name: 'Zimbabue', prefix: '+263' },
  { code: 'AL', name: 'Albania', prefix: '+355' },
  { code: 'DE', name: 'Alemania', prefix: '+49' },
  { code: 'AD', name: 'Andorra', prefix: '+376' },
  { code: 'AT', name: 'Austria', prefix: '+43' },
  { code: 'BE', name: 'Bélgica', prefix: '+32' },
  { code: 'BY', name: 'Bielorrusia', prefix: '+375' },
  { code: 'BA', name: 'Bosnia y Herzegovina', prefix: '+387' },
  { code: 'BG', name: 'Bulgaria', prefix: '+359' },
  { code: 'CY', name: 'Chipre', prefix: '+357' },
  { code: 'HR', name: 'Croacia', prefix: '+385' },
  { code: 'DK', name: 'Dinamarca', prefix: '+45' },
  { code: 'SK', name: 'Eslovaquia', prefix: '+421' },
  { code: 'SI', name: 'Eslovenia', prefix: '+386' },
  { code: 'ES', name: 'España', prefix: '+34' },
  { code: 'EE', name: 'Estonia', prefix: '+372' },
  { code: 'FI', name: 'Finlandia', prefix: '+358' },
  { code: 'FR', name: 'Francia', prefix: '+33' },
  { code: 'GE', name: 'Georgia', prefix: '+995' },
  { code: 'GR', name: 'Grecia', prefix: '+30' },
  { code: 'HU', name: 'Hungría', prefix: '+36' },
  { code: 'IE', name: 'Irlanda', prefix: '+353' },
  { code: 'IS', name: 'Islandia', prefix: '+354' },
  { code: 'IT', name: 'Italia', prefix: '+39' },
  { code: 'XK', name: 'Kosovo', prefix: '+383' },
  { code: 'LV', name: 'Letonia', prefix: '+371' },
  { code: 'LI', name: 'Liechtenstein', prefix: '+423' },
  { code: 'LT', name: 'Lituania', prefix: '+370' },
  { code: 'LU', name: 'Luxemburgo', prefix: '+352' },
  { code: 'MK', name: 'Macedonia del Norte', prefix: '+389' },
  { code: 'MT', name: 'Malta', prefix: '+356' },
  { code: 'MD', name: 'Moldavia', prefix: '+373' },
  { code: 'MC', name: 'Mónaco', prefix: '+377' },
  { code: 'ME', name: 'Montenegro', prefix: '+382' },
  { code: 'NO', name: 'Noruega', prefix: '+47' },
  { code: 'NL', name: 'Países Bajos', prefix: '+31' },
  { code: 'PL', name: 'Polonia', prefix: '+48' },
  { code: 'PT', name: 'Portugal', prefix: '+351' },
  { code: 'GB', name: 'Reino Unido', prefix: '+44' },
  { code: 'CZ', name: 'República Checa', prefix: '+420' },
  { code: 'RO', name: 'Rumanía', prefix: '+40' },
  { code: 'RU', name: 'Rusia', prefix: '+7' },
  { code: 'SM', name: 'San Marino', prefix: '+378' },
  { code: 'RS', name: 'Serbia', prefix: '+381' },
  { code: 'SE', name: 'Suecia', prefix: '+46' },
  { code: 'CH', name: 'Suiza', prefix: '+41' },
  { code: 'TR', name: 'Turquía', prefix: '+90' },
  { code: 'UA', name: 'Ucrania', prefix: '+380' },
  { code: 'VA', name: 'Vaticano', prefix: '+379' },
  { code: 'AG', name: 'Antigua y Barbuda', prefix: '+1' },
  { code: 'AR', name: 'Argentina', prefix: '+54' },
  { code: 'BS', name: 'Bahamas', prefix: '+1' },
  { code: 'BB', name: 'Barbados', prefix: '+1' },
  { code: 'BZ', name: 'Belice', prefix: '+501' },
  { code: 'BO', name: 'Bolivia', prefix: '+591' },
  { code: 'BR', name: 'Brasil', prefix: '+55' },
  { code: 'CA', name: 'Canadá', prefix: '+1' },
  { code: 'CL', name: 'Chile', prefix: '+56' },
  { code: 'CO', name: 'Colombia', prefix: '+57' },
  { code: 'CR', name: 'Costa Rica', prefix: '+506' },
  { code: 'CU', name: 'Cuba', prefix: '+53' },
  { code: 'DM', name: 'Dominica', prefix: '+1' },
  { code: 'DO', name: 'República Dominicana', prefix: '+1' },
  { code: 'EC', name: 'Ecuador', prefix: '+593' },
  { code: 'SV', name: 'El Salvador', prefix: '+503' },
  { code: 'US', name: 'Estados Unidos', prefix: '+1' },
  { code: 'GD', name: 'Granada', prefix: '+1' },
  { code: 'GT', name: 'Guatemala', prefix: '+502' },
  { code: 'GY', name: 'Guyana', prefix: '+592' },
  { code: 'HT', name: 'Haití', prefix: '+509' },
  { code: 'HN', name: 'Honduras', prefix: '+504' },
  { code: 'JM', name: 'Jamaica', prefix: '+1' },
  { code: 'MX', name: 'México', prefix: '+52' },
  { code: 'NI', name: 'Nicaragua', prefix: '+505' },
  { code: 'PA', name: 'Panamá', prefix: '+507' },
  { code: 'PY', name: 'Paraguay', prefix: '+595' },
  { code: 'PE', name: 'Perú', prefix: '+51' },
  { code: 'KN', name: 'San Cristóbal y Nieves', prefix: '+1' },
  { code: 'LC', name: 'Santa Lucía', prefix: '+1' },
  { code: 'VC', name: 'San Vicente y las Granadinas', prefix: '+1' },
  { code: 'SR', name: 'Surinam', prefix: '+597' },
  { code: 'TT', name: 'Trinidad y Tobago', prefix: '+1' },
  { code: 'UY', name: 'Uruguay', prefix: '+598' },
  { code: 'VE', name: 'Venezuela', prefix: '+58' },
];

export const REGISTER_COUNTRIES = [
  'Afganistán',
  'Albania',
  'Alemania',
  'Andorra',
  'Angola',
  'Antigua y Barbuda',
  'Arabia Saudita',
  'Argelia',
  'Argentina',
  'Armenia',
  'Austria',
  'Azerbaiyán',
  'Bahamas',
  'Barbados',
  'Bélgica',
  'Belice',
  'Benín',
  'Bielorrusia',
  'Bolivia',
  'Bosnia y Herzegovina',
  'Botsuana',
  'Brasil',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Camerún',
  'Canadá',
  'Chad',
  'Chile',
  'Chipre',
  'Colombia',
  'Comoras',
  'Congo',
  'Costa Rica',
  'Costa de Marfil',
  'Croacia',
  'Cuba',
  'Dinamarca',
  'Dominica',
  'Ecuador',
  'Egipto',
  'El Salvador',
  'Emiratos Árabes Unidos',
  'Eritrea',
  'Eslovaquia',
  'Eslovenia',
  'España',
  'Estados Unidos',
  'Estonia',
  'Esuatini',
  'Etiopía',
  'Finlandia',
  'Francia',
  'Gabón',
  'Gambia',
  'Georgia',
  'Ghana',
  'Granada',
  'Grecia',
  'Guatemala',
  'Guinea',
  'Guinea-Bisáu',
  'Guinea Ecuatorial',
  'Guyana',
  'Haití',
  'Honduras',
  'Hungría',
  'Irlanda',
  'Islandia',
  'Israel',
  'Italia',
  'Jamaica',
  'Jordania',
  'Kazajistán',
  'Kenia',
  'Kirguistán',
  'Kosovo',
  'Kuwait',
  'Letonia',
  'Líbano',
  'Liberia',
  'Libia',
  'Liechtenstein',
  'Lituania',
  'Luxemburgo',
  'Macedonia del Norte',
  'Madagascar',
  'Malaui',
  'Malí',
  'Malta',
  'Marruecos',
  'Mauricio',
  'Mauritania',
  'México',
  'Micronesia',
  'Moldavia',
  'Mónaco',
  'Montenegro',
  'Mozambique',
  'Namibia',
  'Nicaragua',
  'Níger',
  'Nigeria',
  'Noruega',
  'Nueva Zelanda',
  'Omán',
  'Países Bajos',
  'Panamá',
  'Paraguay',
  'Perú',
  'Polonia',
  'Portugal',
  'Qatar',
  'Reino Unido',
  'República Centroafricana',
  'República Checa',
  'República Democrática del Congo',
  'República Dominicana',
  'Rumanía',
  'Ruanda',
  'Rusia',
  'San Cristóbal y Nieves',
  'San Marino',
  'San Vicente y las Granadinas',
  'Santa Lucía',
  'Santo Tomé y Príncipe',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leona',
  'Somalia',
  'Sri Lanka',
  'Sudáfrica',
  'Sudán',
  'Sudán del Sur',
  'Suecia',
  'Suiza',
  'Surinam',
  'Tanzania',
  'Tayikistán',
  'Togo',
  'Trinidad y Tobago',
  'Túnez',
  'Turkmenistán',
  'Turquía',
  'Ucrania',
  'Uganda',
  'Uruguay',
  'Uzbekistán',
  'Vaticano',
  'Venezuela',
  'Yemen',
  'Yibuti',
  'Zambia',
  'Zimbabue',
] as const;

export function getCountryByPrefix(prefix: string) {
  return COUNTRIES.find((country) => country.prefix === prefix);
}

export function getCountryByCode(code: string) {
  return COUNTRIES.find((country) => country.code === code);
}
