export const REGISTER_COUNTRIES = [
  'Afganistán',
  'Albania',
  'Alemania',
  'Andorra',
  'Angola',
  'Antigua y Barbuda',
  'Arabia Saudita',
  'Argelia',
  'Argentina',
  'Armenia',
  'Austria',
  'Azerbaiyán',
  'Bahamas',
  'Barbados',
  'Bélgica',
  'Belice',
  'Benín',
  'Bielorrusia',
  'Bolivia',
  'Bosnia y Herzegovina',
  'Botsuana',
  'Brasil',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Camerún',
  'Canadá',
  'Chad',
  'Chile',
  'Chipre',
  'Colombia',
  'Comoras',
  'Congo',
  'Costa Rica',
  'Costa de Marfil',
  'Croacia',
  'Cuba',
  'Dinamarca',
  'Dominica',
  'Ecuador',
  'Egipto',
  'El Salvador',
  'Emiratos Árabes Unidos',
  'Eritrea',
  'Eslovaquia',
  'Eslovenia',
  'España',
  'Estados Unidos',
  'Estonia',
  'Esuatini',
  'Etiopía',
  'Finlandia',
  'Francia',
  'Gabón',
  'Gambia',
  'Georgia',
  'Ghana',
  'Granada',
  'Grecia',
  'Guatemala',
  'Guinea',
  'Guinea-Bisáu',
  'Guinea Ecuatorial',
  'Guyana',
  'Haití',
  'Honduras',
  'Hungría',
  'Irlanda',
  'Islandia',
  'Israel',
  'Italia',
  'Jamaica',
  'Jordania',
  'Kazajistán',
  'Kenia',
  'Kirguistán',
  'Kosovo',
  'Kuwait',
  'Letonia',
  'Líbano',
  'Liberia',
  'Libia',
  'Liechtenstein',
  'Lituania',
  'Luxemburgo',
  'Macedonia del Norte',
  'Madagascar',
  'Malaui',
  'Malí',
  'Malta',
  'Marruecos',
  'Mauricio',
  'Mauritania',
  'México',
  'Micronesia',
  'Moldavia',
  'Mónaco',
  'Montenegro',
  'Mozambique',
  'Namibia',
  'Nicaragua',
  'Níger',
  'Nigeria',
  'Noruega',
  'Nueva Zelanda',
  'Omán',
  'Países Bajos',
  'Panamá',
  'Paraguay',
  'Perú',
  'Polonia',
  'Portugal',
  'Qatar',
  'Reino Unido',
  'República Centroafricana',
  'República Checa',
  'República Democrática del Congo',
  'República Dominicana',
  'Rumanía',
  'Ruanda',
  'Rusia',
  'San Cristóbal y Nieves',
  'San Marino',
  'San Vicente y las Granadinas',
  'Santa Lucía',
  'Santo Tomé y Príncipe',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leona',
  'Somalia',
  'Sri Lanka',
  'Sudáfrica',
  'Sudán',
  'Sudán del Sur',
  'Suecia',
  'Suiza',
  'Surinam',
  'Tanzania',
  'Tayikistán',
  'Togo',
  'Trinidad y Tobago',
  'Túnez',
  'Turkmenistán',
  'Turquía',
  'Ucrania',
  'Uganda',
  'Uruguay',
  'Uzbekistán',
  'Vaticano',
  'Venezuela',
  'Yemen',
  'Yibuti',
  'Zambia',
  'Zimbabue',
] as const;
